config/routes.rb
Rails.application.routes.draw do
  devise_for :users
        root to: 'articles#index'
  	resources :articles do
	    resources :comments
        end
        resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	has_many :taggings, dependent: :destroy
	has_many :tags , through: :taggings
	def tag_list=(tags_string)
	  tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
	  new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
	  self.tags = new_or_found_tags
end
	def tag_list
  self.tags.map(&:name).join(', ')
end



end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :articles , through: :taggings
	def to_s
		name
	end
	

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable , :lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
        include ArticlesHelper
	def index
		@articles = Article.all
	end
	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id =@article.id
	end
	def new
		@article =Article.new
	end
	def create 
		@article =Article.new(article_params)
		@article.save
		flash.notice="Article '#{@article.title}' created"
		redirect_to article_path(@article)
	end
	def destroy
		@article =Article.find(params[:id])
		@article.destroy
		flash.notice ="Article '#{@article.title}' Deleted"
		redirect_to articles_path
	end
	def edit
		@article =Article.find(params[:id])
	end
	def update
		@article =Article.find(params[:id])
		@article.update(article_params)
		flash.notice ="Article '#{@article.title}'Updated"
		redirect_to article_path(@article)
	end
	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
	  @comment = Comment.new(comment_params)
	  @comment.article_id = params[:article_id]

	  @comment.save

	  redirect_to article_path(@comment.article)
	end

	def comment_params
	  params.require(:comment).permit(:author_name, :body)
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
	  @tag = Tag.find(params[:id])
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	 def article_params
    			params.require(:article).permit(:title, :body, :tag_list)
  	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div class="comment_style">
  <h4 class="comments_by">Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
  <p class="posted_by">Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
  <br>
  <br>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

<div class ="create_container">

  
  <h3 class="tags">
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </h3>

  <h3 class="title">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </h3>

  <h3 class="body">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </h3>
  <p class="submit_button">
    <%= f.submit %>
  </p>

<% end %>
</div>

app/views/articles/edit.html.erb
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>Articles</h1>


  <% @articles.each do |article| %>
    <div class="container">
      <%= link_to article.title, article_path(article) %>
      <br><br>
      <%= article.body %>
    </div>
  <% end %>


<%= link_to "NEW ARTICLE", new_article_path, class: "button" %>

app/views/articles/new.html.erb
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1 class="show_article"><%= @article.title %></h1>
<div class="container">

<h4>
  Body :
<%= @article.body %></p>
<h4>
  Tags :
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
   <%= link_to "Back to Articles", articles_path %>
.
<%= link_to "Delete", article_path(@article), method: :delete ,data: { confirm: 'Are you sure?' }%>
.
<%= link_to "Edit", edit_article_path(@article) %>

</div>
<br><br>
<div class="container">
<%= render partial: 'comments/form' %>
<br>
</div>
<div class="container">
<h3>Comments (<%= @article.comments.size %>)</h3>

<%= render partial: 'articles/comment', collection: @article.comments.reverse %>

<br>
</div>

app/views/comments/_form.html.erb
<h3 class="post_comment">Post a Comment</h3>

<%= form_for [ @article, @comment ],:html=>{:class => 'submit-form'} do |f| %>
  <p>
    <p class="text_label"><%= f.label :author_name,"Your Name" %></p>
    
    <%= f.text_field :author_name, :class => "author" %>
  </p>
  <p>
    <%= f.label :body %><br/>
    <br>
    <%= f.text_area :body ,:class => "author" %>
  </p>
  <p>
    <%= f.submit 'Submit' ,:class=> "buttons" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class ="header">
    </div>
    <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>
    <div class ="footer">

    </div>
    <div class="flash">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    </div>
    <%= yield %>

  </body>
</html>

app/views/tags/index.html.erb
<h2>List of Tags</h2>
<ul id="tags">
  <% @tags.each do |article| %>
    <li>
      <%= article.tag %>
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<div class="containers">
  <% @tag.articles.each do |article| %>
    <h2><%= article.title %></h2>
    <%= link_to "Show Article", article_path(article) %>
    <br>
  <% end %>
</div>